version: '2'
services:
  taiko-web-server:
    build: .
    container_name: taiko-server
    ports:
      - '80:80'
    volumes:
      - './db/taiko.db:/srv/taiko-web/taiko.db'
      - './songs:/srv/taiko-web/public/songs'
      - './etc/config.json:/srv/taiko-web/config.json'
